### ISSUE TITLE
Create RPM for Node 8.1.3

### ISSUE THREAD

**Issue by danbev** [bucharest-gold/node-rpm#11]
Node 8.1.1 will be released shortly and when this happens we should build a RPM for it by following the instructions in https://github.com/danbev/node-rpm#building-a-new-rpm.

**Comment by danbev** [comment]
The  8.1.1 tag is now available:
https://github.com/nodejs/node/tree/v8.1.1

**Comment by danbev** [comment]
Note sure if this will affect us but it might be worth waiting until there is another build of the release. Please see this issue comment for details:
https://github.com/nodejs/node/issues/13667#issuecomment-308338830

**Comment by helio-frota** [comment]
Can't build 8.1.3 - maybe I'm missing more steps:

0. using v8.x-staging branch **git checkout -b v8.x-staging origin/v8.x-staging**
1. modified nodejs.spec only this part `from %global nodejs_patch 1 to %global nodejs_patch 3`
2. executed the command `docker build -t bucharestgold/fedora-node .`
3. executed the command `docker run -it -v ${PWD}/rpms:/root/rpmbuild/RPMS bucharestgold/fedora-node`
3. Answered `n` (no) to the patches and got errors:

```
$ docker run -it -v ${PWD}/rpms:/root/rpmbuild/RPMS bucharestgold/fedora-node
Building with version 8.1.3
old_build_dir: /root/rpmbuild_usr_src_debug/BUILD/nodejs
new_build_dir: /root/rpmbuild_usr_src_debug/BUILD/node-v8.1.3
~/rpmbuild_usr_src_debug/BUILD/node-v8.1.3 /usr/src/node-rpm
Checking out files: 100% (21958/21958), done.
Switched to a new branch '8.1.3'
tar: Removing leading `/' from member names
/usr/src/node-rpm
~/rpmbuild_usr_src_debug/BUILD /usr/src/node-rpm
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.J7v94G
+ umask 022
+ cd /root/rpmbuild_usr_src_debug/BUILD
+ cd /root/rpmbuild_usr_src_debug/BUILD
+ cd node-v8.1.3
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ echo 'Patch #2 (0003-CA-Certificates-are-provided-by-Fedora.patch):'
Patch #2 (0003-CA-Certificates-are-provided-by-Fedora.patch):
+ /usr/bin/patch --no-backup-if-mismatch -p1 --fuzz=0
patching file src/node_crypto.cc
+ echo 'Patch #3 (0004-Intl-test.patch):'
Patch #3 (0004-Intl-test.patch):
+ /usr/bin/patch --no-backup-if-mismatch -p1 --fuzz=0
patching file test/common/index.js
Hunk #1 succeeded at 696 (offset 7 lines).
patching file test/parallel/test-icu-data-dir.js
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file test/parallel/test-icu-data-dir.js.rej
patching file test/parallel/test-url-domain-ascii-unicode.js
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file test/parallel/test-url-domain-ascii-unicode.js.rej
patching file test/parallel/test-url-format-whatwg.js
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file test/parallel/test-url-format-whatwg.js.rej
error: Bad exit status from /var/tmp/rpm-tmp.J7v94G (%prep)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.J7v94G (%prep)
/usr/src/node-rpm
```

> ( containers removed, images removed )

Doing the same steps again but answered `y`(yes) to the patches:

```
$ docker run -it -v ${PWD}/rpms:/root/rpmbuild/RPMS bucharestgold/fedora-node
Building with version 8.1.3
old_build_dir: /root/rpmbuild_usr_src_debug/BUILD/nodejs
new_build_dir: /root/rpmbuild_usr_src_debug/BUILD/node-v8.1.3
~/rpmbuild_usr_src_debug/BUILD/node-v8.1.3 /usr/src/node-rpm
Checking out files: 100% (21958/21958), done.
Switched to a new branch '8.1.3'
tar: Removing leading `/' from member names
/usr/src/node-rpm
~/rpmbuild_usr_src_debug/BUILD /usr/src/node-rpm
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.Hd4XG0
+ umask 022
+ cd /root/rpmbuild_usr_src_debug/BUILD
+ cd /root/rpmbuild_usr_src_debug/BUILD
+ cd node-v8.1.3
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ echo 'Patch #2 (0003-CA-Certificates-are-provided-by-Fedora.patch):'
Patch #2 (0003-CA-Certificates-are-provided-by-Fedora.patch):
+ /usr/bin/patch --no-backup-if-mismatch -p1 --fuzz=0
patching file src/node_crypto.cc
+ echo 'Patch #3 (0004-Intl-test.patch):'
Patch #3 (0004-Intl-test.patch):
+ /usr/bin/patch --no-backup-if-mismatch -p1 --fuzz=0
patching file test/common/index.js
Hunk #1 succeeded at 696 (offset 7 lines).
patching file test/parallel/test-icu-data-dir.js
Reversed (or previously applied) patch detected!  Assume -R? [n] y
patching file test/parallel/test-url-domain-ascii-unicode.js
Reversed (or previously applied) patch detected!  Assume -R? [n] y
patching file test/parallel/test-url-format-whatwg.js
Reversed (or previously applied) patch detected!  Assume -R? [n] y
+ echo 'Patch #4 (0005-Zlib-test.patch):'
Patch #4 (0005-Zlib-test.patch):
+ /usr/bin/patch --no-backup-if-mismatch -p1 --fuzz=0
patching file test/parallel/test-zlib-failed-init.js
Hunk #1 FAILED at 6.
1 out of 1 hunk FAILED -- saving rejects to file test/parallel/test-zlib-failed-init.js.rej
error: Bad exit status from /var/tmp/rpm-tmp.Hd4XG0 (%prep)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Hd4XG0 (%prep)
/usr/src/node-rpm
```

**Comment by danbev** [comment]
The error is because the patch for that patch cannot be applied. I need to
double check but I think the three test patches can be removed now that
they landed upstream. You can try by commenting out the patch3, patch4 and
patch5 in nodejs.spec and then rebuilding the image.

ons 12 juli 2017 kl. 15:12 skrev helio-frota <notifications@github.com>:

**Comment by helio-frota** [comment]
@danbev thanks for the tip !
right now I'm doing exactly what the travis do for 8.1.2 version.

`git clone --depth=50 --branch=v8.x-staging https://github.com/bucharest-gold/node-rpm.git bucharest-gold/node-rpm`

to see what happen, after this - if not work - I'll use your tip to try to build.

**Comment by helio-frota** [comment]
no luck following travis steps

```
docker run -it -v ${PWD}/rpms:/root/rpmbuild/RPMS bucharestgold/fedora-node
Building with version 8.1.3
old_build_dir: /root/rpmbuild_usr_src_debug/BUILD/nodejs
new_build_dir: /root/rpmbuild_usr_src_debug/BUILD/node-v8.1.3
~/rpmbuild_usr_src_debug/BUILD/node-v8.1.3 /usr/src/node-rpm
Checking out files: 100% (21958/21958), done.
Switched to a new branch '8.1.3'
tar: Removing leading `/' from member names
/usr/src/node-rpm
~/rpmbuild_usr_src_debug/BUILD /usr/src/node-rpm
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.NzsRTw
+ umask 022
+ cd /root/rpmbuild_usr_src_debug/BUILD
+ cd /root/rpmbuild_usr_src_debug/BUILD
+ cd node-v8.1.3
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ echo 'Patch #2 (0003-CA-Certificates-are-provided-by-Fedora.patch):'
Patch #2 (0003-CA-Certificates-are-provided-by-Fedora.patch):
+ /usr/bin/patch --no-backup-if-mismatch -p1 --fuzz=0
patching file src/node_crypto.cc
+ echo 'Patch #3 (0004-Intl-test.patch):'
Patch #3 (0004-Intl-test.patch):
+ /usr/bin/patch --no-backup-if-mismatch -p1 --fuzz=0
patching file test/common/index.js
Hunk #1 succeeded at 696 (offset 7 lines).
patching file test/parallel/test-icu-data-dir.js
Reversed (or previously applied) patch detected!  Assume -R? [n] y
patching file test/parallel/test-url-domain-ascii-unicode.js
Reversed (or previously applied) patch detected!  Assume -R? [n] y
patching file test/parallel/test-url-format-whatwg.js
Reversed (or previously applied) patch detected!  Assume -R? [n] y
+ echo 'Patch #4 (0005-Zlib-test.patch):'
Patch #4 (0005-Zlib-test.patch):
+ /usr/bin/patch --no-backup-if-mismatch -p1 --fuzz=0
patching file test/parallel/test-zlib-failed-init.js
Hunk #1 FAILED at 6.
1 out of 1 hunk FAILED -- saving rejects to file test/parallel/test-zlib-failed-init.js.rej
error: Bad exit status from /var/tmp/rpm-tmp.NzsRTw (%prep)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.NzsRTw (%prep)
/usr/src/node-rpm
```

going to use your strategy now

**Comment by helio-frota** [comment]
After comment the 3 patches the build start fine, the tests executed fine but after that
we got error:


```
.....
[==========] 46 tests from 6 test cases ran. (122 ms total)
[  PASSED  ] 46 tests.
/usr/bin/python tools/test.py --mode=release -J \
	async-hooks doctool inspector known_issues message parallel pseudo-tty sequential \
	addons addons-napi
=== release test-crypto-fips ===                                               
Path: parallel/test-crypto-fips
Spawned child [pid:20863] with cmd 'require("crypto").fips' expect 0 with args '' OPENSSL_CONF=""
Child #1 [pid:20863] OK.
Spawned child [pid:20875] with cmd 'require("crypto").fips' expect "bad option" with args '--enable-fips' OPENSSL_CONF=undefined
Child #2 [pid:20875] OK.
Spawned child [pid:20876] with cmd 'require("crypto").fips' expect "bad option" with args '--force-fips' OPENSSL_CONF=undefined
Child #3 [pid:20876] OK.
Spawned child [pid:20881] with cmd 'require("crypto").fips' expect 0 with args '--openssl-config=/root/rpmbuild_usr_src_debug/BUILD/nodejs/test/fixtures/openssl_fips_enabled.cnf' OPENSSL_CONF=undefined
assert.js:60
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: 0 === 1
    at responseHandler (/root/rpmbuild_usr_src_debug/BUILD/nodejs/test/parallel/test-crypto-fips.js:56:14)
    at testHelper (/root/rpmbuild_usr_src_debug/BUILD/nodejs/test/parallel/test-crypto-fips.js:61:3)
    at Object.<anonymous> (/root/rpmbuild_usr_src_debug/BUILD/nodejs/test/parallel/test-crypto-fips.js:89:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
Command: out/Release/node /root/rpmbuild_usr_src_debug/BUILD/nodejs/test/parallel/test-crypto-fips.js
[02:21|% 100|+ 1601|-   1]: Done                                               
Makefile:196: recipe for target 'test' failed
make: *** [test] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.9NQa0f (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.9NQa0f (%build)
/usr/src/node-rpm
```

**Comment by helio-frota** [comment]
going to try again uncommenting the fips patch.

**Comment by helio-frota** [comment]
working

```
Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild_usr_src_debug/BUILDROOT/nodejs-8.1.3-1.fc25.x86_64
Wrote: /root/rpmbuild_usr_src_debug/SRPMS/nodejs-8.1.3-1.fc25.src.rpm
Wrote: /root/rpmbuild_usr_src_debug/RPMS/x86_64/nodejs-8.1.3-1.fc25.x86_64.rpm
Wrote: /root/rpmbuild_usr_src_debug/RPMS/x86_64/nodejs-devel-8.1.3-1.fc25.x86_64.rpm
Wrote: /root/rpmbuild_usr_src_debug/RPMS/x86_64/npm-5.0.3-1.8.1.3.1.fc25.x86_64.rpm
Wrote: /root/rpmbuild_usr_src_debug/RPMS/noarch/nodejs-docs-8.1.3-1.fc25.noarch.rpm
Wrote: /root/rpmbuild_usr_src_debug/RPMS/x86_64/nodejs-debuginfo-8.1.3-1.fc25.x86_64.rpm
/usr/src/node-rpm
```
but when I go to this directory:  `/root/rpmbuild_usr_src_debug/RPMS/` it is showing nothing

```
[root@dd0cd097039f RPMS]# pwd
/root/rpmbuild_usr_src_debug/RPMS
[root@dd0cd097039f RPMS]# ll
total 0

[root@dd0cd097039f rpmbuild_usr_src_debug]# ll
total 24
drwxr-xr-x 3 root root 4096 Jul  5 14:50 BUILD
drwxr-xr-x 2 root root 4096 Jul  5 14:32 BUILDROOT
drwxr-xr-x 2 root root 4096 Jul  5 14:25 RPMS
drwxr-xr-x 1 root root 4096 Jul 12 16:31 SOURCES
drwxr-xr-x 1 root root 4096 Jul 12 16:31 SPECS
drwxr-xr-x 2 root root 4096 Jul  5 14:32 SRPMS
[root@dd0cd097039f rpmbuild_usr_src_debug]# cd RPMS/
[root@dd0cd097039f RPMS]# ll
total 0

```

**Comment by helio-frota** [comment]
going to try './run.sh' maybe the other way is making some cleanup ( I dunno )

**Comment by helio-frota** [comment]
working with `./run.sh`

```
[root@5c62e1db5354 RPMS]# cd x86_64/
[root@5c62e1db5354 x86_64]# ll
total 105384
-rw-r--r-- 1 root root  6218658 Jul 12 18:11 nodejs-8.1.3-1.fc25.x86_64.rpm
-rw-r--r-- 1 root root 98070906 Jul 12 18:12 nodejs-debuginfo-8.1.3-1.fc25.x86_64.rpm
-rw-r--r-- 1 root root   129750 Jul 12 18:11 nodejs-devel-8.1.3-1.fc25.x86_64.rpm
-rw-r--r-- 1 root root  3485106 Jul 12 18:11 npm-5.0.3-1.8.1.3.1.fc25.x86_64.rpm
```

**Comment by lance** [comment]
Ended up on 8.1.4
